admin:
  password: ${ADMIN_PASSWORD:}

server:
  address: 127.0.0.1
  port: ${APP_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/music_diary?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

file:
  upload-dir: ${UPLOAD_DIR:./uploads/}
  access-url-prefix: ${UPLOAD_URL_PREFIX:/uploads/}
